name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  test:
    runs-n: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run tests
      run: |
        pytest tests/unit tests/integration -v
